# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder, MultiScaleMaskedTransformerDecoder_mp, MultiScaleMaskedTransformerDecoderFASeg, MultiScaleMaskedTransformerDecoderFASeg_onlyDH, MultiScaleMaskedTransformerDecoderFASeg_onlyDQ,MultiScaleMaskedTransformerDecoder_OurDH_v3, MultiScaleMaskedTransformerDecoder_OurDH_v4, MultiScaleMaskedTransformerDecoder_OurDH_v5
